server:
  port: 9191


spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
      routes:
       
        - id: user-service
          uri: http://localhost:8098/userservice/
          predicates:
            - Path= /userservice/** 
        - id: book-service
          uri: http://localhost:8097/bookservice/
          predicates:
            - Path=/bookservice/**
        - id: admin-service
          uri: http://localhost:8094/adminservice/
          predicates:
            - Path=/adminservice/** 
            
  
#  
#eureka:            
#  instance:
#    hostname: localhost 